version: '3.8'
services:
  wechatpchook:
    container_name: comwechat
    environment:
        - VNCPASS=YourPassword
        - COMWECHAT=https://github.com/ljc545w/ComWeChatRobot/releases/download/3.7.0.30-0.1.0-pre/3.7.0.30-0.1.0-pre.zip
    volumes:
        - "/root/WeChat/Files/:/home/user/.wine/drive_c/users/user/My Documents/WeChat Files/"
        - "/root/WeChat/Data/:/home/user/.wine/drive_c/users/user/Application Data/"
    privileged: true
    network_mode: host
    image: tomsnow1999/docker-com_wechat_robot:latest
    restart: unless-stopped
  efb:
    image: ghcr.io/2018wzh/efb-docker:latest
    container_name: efb
    volumes:
      - ./data/ehforward_config:/opt/app/ehforward_config
    restart: unless-stopped