name: docker-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v2

    - name: build and deploy master image to ghcr.io
      # if: ${{ github.ref == 'refs/heads/master' }}
      env:
        PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.actor }}
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
        echo ${PKG_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
        docker build -t ghcr.io/${USERNAME}/efb-docker:${git_branch}-${git_hash} -t ghcr.io/${USERNAME}/efb-docker:latest .
        docker push ghcr.io/${USERNAME}/efb-docker:${git_branch}-${git_hash}
        docker push ghcr.io/${USERNAME}/efb-docker:latest